env  = "DB1"
name = "tab2"
type = "db_node"
desc = "This is a database table"
tags = ["sometag", "someothertag"]
depends = "RE1.tab2"
con_code = "DB1$con"

r_code = '''
{
  DBI::dbWriteTable(conn = DB1$con, name = 'tab2', value = RE1$tab2, overwrite = TRUE)
}
'''
