env  = "files"
name = "iris_aggr_excel"
path = "./inst/db2/data/iris_aggr.xlsx"
type = "file_node"

depends = ["RE1.iristab"]

r_code = '''
{
  openxlsx::write.xlsx(RE1$iristab, file = self$path)
}
'''
