# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: false

r_packages:
  - covr
  - crayon
  - data.table
  - DBI
  - JuliaCall
  - methods
  - reticulate
  - R6
  - RSQLite
  - stringr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    packages:
      - python3
      - python3-numpy
      - python3-pandas
